project_id = "qtygqlpqetkjzklqgqzr"

[functions.generate-google-wallet]
enabled = true
verify_jwt = true
import_map = "./functions/generate-google-wallet/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-google-wallet/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-google-wallet/*.html" ]

[functions.sync-google-wallet]
enabled = true
verify_jwt = true
entrypoint = "./functions/sync-google-wallet/index.ts"

[functions.send-google-wallet-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-google-wallet-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-google-wallet-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-google-wallet-notification/*.html" ]

[functions.send-demo-request]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-demo-request/index.ts"

[functions.send-transactional-email]
enabled = true
verify_jwt = true
entrypoint = "./functions/send-transactional-email/index.ts"

[functions.send-auth-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-auth-email/index.ts"

[functions.create-checkout-session]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-checkout-session/index.ts"

[functions.create-billing-portal]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-billing-portal/index.ts"

[functions.create-store-checkout]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-store-checkout/index.ts"

[functions.stripe-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/stripe-webhook/index.ts"

[functions.register-business-account]
enabled = true
verify_jwt = false
entrypoint = "./functions/register-business-account/index.ts"
