create table if not exists public.email_rate_limits (
  id bigint generated by default as identity primary key,
  key_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists email_rate_limits_key_created_idx
  on public.email_rate_limits (key_hash, created_at desc);

alter table public.email_rate_limits enable row level security;
revoke all on public.email_rate_limits from public, anon, authenticated;
grant all on public.email_rate_limits to service_role;

